apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: deployment
    kind: Deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
