apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

namePrefix: plate-
labels:
  - includeSelectors: true
    pairs:
      app: plate
