apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.tls.email }}
    privateKeySecretRef:
      name: tls-secret
    solvers:
    - http01:
        ingress:
          class: nginx