apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data: 
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data: 
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}