apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plate-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: k8s.lucassegundo.work
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: plate-service
                port:
                  number: 3000
