app:
  namespace: 'dev'
  image: 'main'
  port: 3000
  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpuPercentage: 80
  limits:
    cpu: '300m'
    memory: '256Mi'

host: ''

configmap:
  name: plate-config
  data: {}

secret:
  name: plate-secret
  data: {}
