---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_DATABASE_URL: AgB6ZOpxXKJi6IM/VCdx+4QfiA8ny5ltqF37WHjJfJgAWdDOycEYLwFRfuOX84JP+d5lCtaxtClsqWk+BXP+MVXu9oe+KicgnoNAU8pipWkqWfH83a8DhWyJVaj+/atC2Q02TpB5clXfVXMZswsHtUWT8oYxsVf85eWfWue8DPeElgbF6LmuggdSdx/+e5wJ0bEflTkpK9/k4smrDRf9iy8WSxS+XwQVs62Pfm6yRgDCo2xTBotdgAKqtkR9OwsfKnZCUEqVyjqAfkPtvhfUsBJaBGjxzMpwKlpr8moJ0vMIdUhgUTqeRGk3F44ZfOyFGPxdx0/jSnMwkCi2+thoKhVUKiJ0JF4gFpsYLHhttgtVlv6Oj7JiDn59gcodmDxh7WfbradPzIArtEEDPcdQxjAzwuTwbjMmi1qiWuL7yK6eW6vRJwLi9ndpPB/tfv/1nu5cPrF6EfJ5UGT5KJwFjQ8ai4VaZAWF69XsMEPrAyK8LIC9jLLaiGeuOr3bllmmeQR0j0AYXvFVIY5vuO+LUtXxk+jSC18gNIwIf4u5CBjyQRLQQGxPPwppjPjhMOmEmRionyULkto1roNZ6XeRE3FFSsmNJxKbgQXWAllW54+ddAH0PkjI3ssHZyFAZYvRo7I1MnEf4pL1SE0dgsaroj2fGc4BZv7xRiTGjo6eypRG2zSGn0fZIIbkISsLcUwzCpzw2IQXT72bXnwuoZIsEjmvhEah3AhpZhLtqdv+Dz4Lw2C9350/tKoXY++KU0+B86Ln0x7S/zLcVhLGFp4sS/iEZkDPFiNv4gbFhJHlGWEE7eoM546Y9WdfVi6twlCeTaaa99rItH6CuX2Kn/YM35E=
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: dev
