---
# Source: helm/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# Source: helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plate-service
  namespace: dev
spec:
  selector:
    app: plate
  ports:
    - port: 3000
      protocol: TCP
  type: ClusterIP
---
# Source: helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plate-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: plate
  template:
    metadata:
      labels:
        app: plate
    spec:
      containers:
        - name: plate
          image: main
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: plate-config
            - secretRef:
                name: plate-secret
---
# Source: helm/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: plate-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: plate-deployment
    kind: Deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
# Source: helm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plate-ingress
  namespace: dev
  
spec:
  
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: plate-service
                port:
                  number: 80
