---
# Source: helm/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: setup-dev-workflow-with-helm
---
# Source: helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plate-service
  namespace: setup-dev-workflow-with-helm
spec:
  selector:
    app: plate
  ports:
    - port: 3000
      protocol: TCP
  type: ClusterIP
---
# Source: helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plate-deployment
  namespace: setup-dev-workflow-with-helm
spec:
  selector:
    matchLabels:
      app: plate
  template:
    metadata:
      labels:
        app: plate
    spec:
      containers:
        - name: plate
          image: lucasfernandesapp/plate:setup_dev_workflow_with_helm
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 3000
          envFrom:
            
            - secretRef:
                name: plate-secret
---
# Source: helm/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: plate-hpa
  namespace: setup-dev-workflow-with-helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: plate-deployment
    kind: Deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
# Source: helm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plate-ingress
  namespace: setup-dev-workflow-with-helm
  
spec:
  
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: plate-service
                port:
                  number: 80
---
# Source: helm/templates/argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucas-segundo/stunning-plate
    path: k8s/manifests/
    targetRevision: setup_dev_workflow_with_helm
    directory:
      include: dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: setup-dev-workflow-with-helm
---
# Source: helm/templates/sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plate-secret
  namespace: setup-dev-workflow-with-helm
spec:
  encryptedData:
    POSTGRES_DATABASE_URL: AgAbIiBqr3zoa5Hlph6pZ4zZQ/6VPcEXNSUbi7fq+5JKUX0TTGqc6VrUPuqW+hm5hdZEZrAkJgyt191b6apdEQv4bbzlswQJITaoByC1kf7fOp3Qe2ImRsKN8lY6C7/I+OA5tNtjbIGviDMlc2g2jeNm6rCB7FKOZA7kjhdfIpvZls7ks+KMzLRgav2ja7xZlXSPgqXlq9W39z1XQPiqAtyXND7F9HM610jeobQnPbeAQ8wB8VDnDTKwp+HsDL9whi2wBlB4kJQrbSaH03tuLbGc9bFTqNCnMVZkgPE+jGjchO6QpfXE/n5HBRepR1iWqp7mmfkG+l0PUWAF3V30VLbWZ5lXZaFnPw29m6LmadTiTVtiEVNv6mP7/uZ+vfk01YvOShOmVvskZY4I/6DKgOrVQDQYN4TaaCt7O/WYm9WcpodDVa0UNkT/UIze9aDYJ1xVFeRmSLwwu+LDixOuaOsq/hk8B3kqx2XXFiFS6zTQTy9+XAdF+A1NMV42xpzZeAJda8uokXUozRtl8mraQPfT63fpLrpniVFV1efQEsJmwOEuZZb9+bJPJTddSze2qb1RTgADC9zEHIaSVSOJY+P0qjnQlpJryLqoVFeIWF5oU78FfnErwjfIKHo/lHZsBSVxJflJA35JpfBNHYYyzbUW2mGqPDEGR3C0hZ2ZMk+Gs/0OVU1983LsnWibiwedXRx1a5Nnirekq1CA9InC9k7F39+KXCbYxIORLq3IjKAhLq/QiBETeiRbnp8cqKlRUcn0XKOsz2oBB82HQM56kmpz8b0pOtrgD+Do4HqNE1P0tOnskJCOWlCmheFfO06vxWUvPu3ar+I6+EBg0mN/VGFdpA+50XDIUw==
  template:
    metadata:
      creationTimestamp: null
      name: plate-secret
      namespace: setup-dev-workflow-with-helm
