---
# Source: helm/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: setup-dev-workflow-with-helm
---
# Source: helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plate-service
  namespace: setup-dev-workflow-with-helm
spec:
  selector:
    app: plate
  ports:
    - port: 3000
      protocol: TCP
  type: ClusterIP
---
# Source: helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plate-deployment
  namespace: setup-dev-workflow-with-helm
spec:
  selector:
    matchLabels:
      app: plate
  template:
    metadata:
      labels:
        app: plate
    spec:
      containers:
        - name: plate
          image: lucasfernandesapp/plate:setup_dev_workflow_with_helm
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 3000
          envFrom:
            
            - secretRef:
                name: plate-secret
---
# Source: helm/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: plate-hpa
  namespace: setup-dev-workflow-with-helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: plate-deployment
    kind: Deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
# Source: helm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plate-ingress
  namespace: setup-dev-workflow-with-helm
  
spec:
  
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: plate-service
                port:
                  number: 80
---
# Source: helm/templates/argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucas-segundo/stunning-plate
    path: k8s/manifests/
    targetRevision: setup_dev_workflow_with_helm
    directory:
      include: dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: setup-dev-workflow-with-helm
---
# Source: helm/templates/sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plate-secret
  namespace: setup-dev-workflow-with-helm
spec:
  encryptedData:
    POSTGRES_DATABASE_URL: AgBPDub6qBXNWr0EictGYnI2B3rHXI2H9Pm8rNdYC1n+cWbm4/SL7IKlS9jOPVfB/gv+Z3+9Mv1StchCi+O3Yb0YGb7ZeCliU8mtEE2vW9O8po0w9s5T0j4fdWwAh+y4/eVRuWUU1qQ4fgqEifYtA9eHm5JBT99aWnrByNDfYsHadEP0nPlZVW5YbCS5VRfABRJShTNxuQNVWKwVTrwtAc2wi2iG5gc2K0baQqZuDOx3CMMGwQlm4Gfipl60IMKyznnjf1MFAPVOn9mESpQj38j8DNeCoGOtXx/bIhgQC9fW9W1DYG9u5TrieiLsfr/bGaHcnydXOoWBQ8nsfxv39tSh1lchAJBS+DVl9Hle9a8DwzS8feT31cY567ZQU3a7j7/vdAKvEuv/CGGTnTHxCMoUS0Y+7aWJn90LyblLx8euXTA1yZRHGhyF3P5wzRtf1XPGf6MEYZ7y2++vRJZTRl9h8D7MtQdvIE0QHckDzMW9mB5Iw5bgGlcHj+4jnlXvUybxZS8S7MfHYSwZ2+TvHxmNE8b+C3KqY3DNJMawYXFhydgVKduHDOzW9Y25yjgVSrmqXgRmXXmMeEV2WdwLEnmoBBYXrn/mQmaK2UXHlYcZ5BdAGrkxUsEdGxXpGhjp8nSIWRAFbHjfottcWlauWCV9wc0Kf8p+r9WqZScY6eMxRMb/iWxX7c6hEBJHoxLsi2yKZA9fF1wcrL+BDCxz7OHB1+XrER8TNr2Dqf3vNvXQQ49S2cWEQHqfeek+o4GA7X4Irbxmuqzatey4Mc8FCySAwVyTfll/AMZQqboT/M71jbXeUzGg6NBuabfoRTiYXnUkoIxyGStJoQaUpRWfRpx9jyzk9puQeA==
  template:
    metadata:
      creationTimestamp: null
      name: plate-secret
      namespace: setup-dev-workflow-with-helm
