---
# Source: helm/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name:
---
# Source: helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plate-service
  namespace: 
spec:
  selector:
    app: plate
  ports:
    - port: 3000
      protocol: TCP
  type: ClusterIP
---
# Source: helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plate-deployment
  namespace: 
spec:
  selector:
    matchLabels:
      app: plate
  template:
    metadata:
      labels:
        app: plate
    spec:
      containers:
        - name: plate
          image: lucasfernandesapp/plate:setup_dev_workflow_with_helm
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 3000
          envFrom:
            
            - secretRef:
                name: plate-secret
---
# Source: helm/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: plate-hpa
  namespace: 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: plate-deployment
    kind: Deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
# Source: helm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plate-ingress
  namespace: 
  
spec:
  
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: plate-service
                port:
                  number: 80
---
# Source: helm/templates/argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucas-segundo/stunning-plate
    path: k8s/manifests/
    targetRevision: setup_dev_workflow_with_helm
    directory:
      include: dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace:
---
# Source: helm/templates/sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plate-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_DATABASE_URL: AgC1RaepgWL0qeuPy8kh4XoF/6gAJFn4mcAiBKHPldNc7sZX2JDvTHO4Om5f2dz2KY7QjAzmCXVHP9vZL4zKUOC7/i3CeWIVVzclbMM4QfaRKcHOHa9/MrZQoEigK53XKu0IwyHC1cubHptibi61rLTSo0MQm0d8J7IcQSkzZA0aeVRelw9fypNDFYXRhGNYFvR+ZkEI/6ZC3POBl0SoOdH0aZDSwIhNXpw2QlSW7sZd6+Bd//8XUcGvX2CuL/uqpLurdN6SO/UvOBPcboiW2VoND9r2WW41fXL20vLIhoL6t5G8aK3XwRrQbt/uXrU5FjZweNg3iTxw8s1V9liUINLrRzaxIOFLiBut2V4F9vDzzI+IQvEdjlE/IetUTUn4PYc9coHclu3C3Du3IIhJU4HWgtz2zrLMaPD3KP+1qq6xNnrHlmb2ZRQocTkUIR3S2ZG0uzdU8oXCbUyexmWQ2JmwN+p0TxD/ges31XqZrjanergVQzr/OhtGVfCy+tlyRV3KwOuZmL7u2Si9/Unv8n6xH3wR1FdUY+9VraQgNaBRiigh4myn55E7HvrxcX4PWaY+pRUFrd+dwNTLOZbTKMGYwFpFRygE4V00X0AjeR8Y61cn2LSd/TC3FQyIHWgmpoIRp8rxW/b1Wp3sbaLmAWbZv+y9l4n3rXslnS50qXYWcdbFxDyBqYZTNRzd/JjXf6jLlIIb2fG9+idsLeg4mv3p0pmDfbUACZvOFQRfmvcQ+MrDbWMvzqfgMATJDjhwilhoxMooam/rMF57zlfpheWj6diX/sesDc7o5rLW/wvbVXl1lKEi86L9UK+hrpgQg9f0F+pDNNpEDTxWf/I9vDpYuTff5dJgMQ==
  template:
    metadata:
      creationTimestamp: null
      name: plate-secret
      namespace: default
