{{ if .Values.configmap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.app.namespace }}
data: 
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
{{ end }}