{{ if .Values.host }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lucas.fernandes.app@gmail.com
    privateKeySecretRef:
      name: tls-secret
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.app.namespace }}
  {{ if .Values.host }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
  {{ end }}
spec:
  {{ if .Values.host }}
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: tls-secret
  {{ end }}
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: {{ .Values.app.port }}
      {{ if .Values.host }}
      host: {{ .Values.host }}
      {{ end }}
