apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.port }}
      protocol: TCP
  type: {{ if .Values.isDevelopment }}LoadBalancer{{ else }}ClusterIP{{ end }}
