app:
  name: plate
  namespace: ''
  port: 3000
  replicas: 2
  limits:
    cpu: '100m'
    memory: '200Mi'
  startupProbe:
    path: /healthz/startup
    failureThreshold: 2
    periodSeconds: 5

isDevelopment: false

host: ''

image:
  repository: ''
  tag: ''

tls:
  email: ''

configmap:
  name: plate-config
  data: {}

secret:
  name: plate-secret
  data: {}
