app:
  name: plate
  namespace: ''
  port: 3000
  replicas: 2
  limits:
    cpu: '300m'
    memory: '256Mi'
  startupProbe:
    isEnabled: true
    path: /healthz/startup
    failureThreshold: 3
    periodSeconds: 10

isDevelopment: false

host: ''

image:
  repository: ''
  tag: ''

tls:
  email: ''

configmap:
  name: plate-config
  data: {}

secret:
  name: plate-secret
  data: {}
