app:
  name: plate
  namespace: ''
  port: 3000
  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpuPercentage: 80
  limits:
    cpu: '300m'
    memory: '256Mi'
  startupProbe:
    isEnabled: true
    path: /healthz/startup
    failureThreshold: 3
    periodSeconds: 5

host: ''

image:
  repository: ''
  tag: ''

tls:
  email: ''

configmap:
  name: plate-config
  data: {}

secret:
  name: plate-secret
  data: {}
