apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: plate-deployment
    kind: Deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
