apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml
- sealed-secret.yaml

patches:
- path: deployment.yaml

namespace: dev
images:
- name: plate
  newName: lucasfernandesapp/plate
  newTag: main-bd62166b6a1cafdfe5deb3322579222a035d3cec
