apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

patches:
- path: deployment.yaml

namespace: dev
images:
- name: plate
  newName: lucasfernandesapp/plate
  newTag: main-4d376232d32dc5f57586080bf6091c2b47ed59b3
