apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

patches:
- path: deployment.yaml

namespace: dev
images:
- name: lucasfernandesapp/plate
  newTag: main-8a5e933518ec180e828c1a476a26a088569e9a2f
- name: plate
  newName: lucasfernandesapp/plate
  newTag: main
