---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plate-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_DATABASE_URL: AgCLS3ash3whihF9Pm8UOCNMVRaLeoxZVSjprFypW7SW1nNLy32Zge4H5x4sytqVHvZTkQahPHXcNjKWgZxhTkB42SSIMAJmInAeokl2umjEfpOgptsc9nyQiE2h7ifQRX5ei7Rzfv4/rd/Cv0iiDAfNAAhxbeEmXaWdtN4n9d+ZCL7Dudw1K1JUOKyqy+Rbc80aG9tFVyG73nbmJWHQn/gfa2LKZRChJj2O0p5pjrd84eccmmtGQm5BDTWP0FCoYxJsTAZHTXLf1GWFfQjkpXQPAaCBhP9Aha/51BuCV/dnU8Viaox56IojX558rCpC9INcfwG7epC4ny/GRCJscHZTrcFpD8rKFMhsiAn4q5zlFB5ASEEFemxMcDYaOS1l5V9H03d1Z7xfJuu1yZLOQHI8CD57corAXOMJKvYxgS9HkLE+wJkc5036yhwIBHFdvI9N4h1nfnq7oMXn2ao5LNFGcxBiCIE7805CAqto7lYe+wUtCYOydj1GuiN6JZQadaraTPeL5iArfeCvi2EkHO45qRqxE5Y+vdNvbmRe/gP0oTmwdY++Ty8WK9zP0twFNTk7ZGhpsoAHnp+LAMPdT/dCULCqyADvrBbhtQz57piOv4BFC8j8IhkdLePV44+2PFP1JRb8cQxlkAI5ya6J5b1uW9vtR1MYuzBAH0w7tx/zA7wcco6Ci9RlCGGbswAooUtKZxpHYqJaKJSqJ7a/l67Fwr9fhgTQ+gI10BLf6fqIl9hNlioWkaEKFKd2X+fqKwF4aJVVy+xjA90ScXmG6BVoT/Un30A9cSusiHIwYNp8suvyqzlL+OsffoKTbVEIeRLp3ILJdmq4apWByjXi6xo=
  template:
    metadata:
      creationTimestamp: null
      name: plate-secret
      namespace: dev
