name: CI/CD

env:
  DOCKER_IMAGE_NAME: plate:${{ github.ref_name }}

on:
  push:
    branches: [main, staging]

jobs:
  ci:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Up Containers
        run: docker compose up -d
        env:
          DOCKER_COMPOSE_COMMAND: ${{ vars.DOCKER_COMPOSE_COMMAND }}
          DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}
          POSTGRES_DATABASE_URL: ${{ vars.DOCKER_POSTGRES_DATABASE_URL }}

      - name: Run unit tests
        run: docker compose exec app npm run test

      - name: Run migrations for testing
        run: docker compose exec app npm run migrate:prod

      - name: Run e2e tests
        run: docker compose exec app npm run test:e2e

      - name: Down Containers
        run: docker compose down

      - name: Run migrations for production
        run: docker run -e POSTGRES_DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }} ${{ env.DOCKER_IMAGE_NAME }} npm run migrate:prod

  cd:
    needs: ci
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Prod Docker image and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          target: prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
