name: CI/CD

env:
  DOCKER_IMAGE_NAME: plate:${{ github.ref_name }}

on:
  push:
    branches: [main, staging]

jobs:
  ci:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create docker image
        run: docker build . -t ${{ env.DOCKER_IMAGE_NAME }} --target dev

      - name: Run unit tests
        run: docker run ${{ env.DOCKER_IMAGE_NAME }} npm run test

      - name: Run migrations
        run: docker run -e POSTGRES_DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }} ${{ env.DOCKER_IMAGE_NAME }} npm run migrate:prod

  cd:
    needs: ci
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Prod Docker image and push to DockerHub
        uses: docker/build-push-action@v6.13.0
        with:
          target: prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        id: install

      - name: Set up kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Upgrade Helm Chart
        shell: bash
        run: helm upgrade --install plate ./helm \
          --set image.tag=${{ github.ref_name }} \
          --set secret.data.DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }}
