name: CI/CD

on:
  push:
    branches: [main, staging]

env:
  DOCKER_IMAGE_REPOSITORY: ${{ vars.REGISTRY_NAME }}/plate
  BRANCH: ${{ github.ref_name }}
  KUBECONFIG_FILE_PATH: ${{ github.workspace }}/kubeconfig

jobs:
  ci:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create docker image
        run: docker build . -t ${{ env.BRANCH }} --target dev

      - name: Run unit tests
        run: docker run ${{ env.BRANCH }} npm run test

      - name: Run migrations
        run: docker run -e POSTGRES_DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }} ${{ env.BRANCH }} npm run migrate:prod

  cd:
    needs: ci
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_NAME }}
          username: ${{ vars.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build Prod Docker image and push
        uses: docker/build-push-action@v6.13.0
        with:
          target: prod
          push: true
          tags: '${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.BRANCH }}'

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBECONFIG }}" > ${{ env.KUBECONFIG_FILE_PATH }}

      - name: Deploy to Kubernetes using Helm
        env:
          KUBECONFIG: ${{ env.KUBECONFIG_FILE_PATH }}
        run: |
          helm upgrade --install plate ./helm \
          --set image.repository=${{ env.DOCKER_IMAGE_REPOSITORY }} \
          --set image.tag=${{ env.BRANCH }} \
          --set secret.data.DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }}
