name: CI/CD

on:
  push:
    branches: [main, staging]

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  ci:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create docker image
        run: docker build . -t ${{ env.BRANCH }} --target dev

      - name: Run unit tests
        run: docker run ${{ env.BRANCH }} npm run test

  cd:
    needs: ci
    environment: ${{ github.ref_name }}
    env:
      DOCKER_IMAGE_REPOSITORY: ${{ vars.REGISTRY_USERNAME }}/plate
      KUBECONFIG_FILE_PATH: ${{ github.workspace }}/kubeconfig
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Prod Docker image and push to registry
        uses: docker/build-push-action@v6.13.0
        with:
          target: prod
          push: true
          tags: '${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.BRANCH }}'
