name: Dev

on:
  push:
    branches-ignore: [main]

jobs:
  ci:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create docker image
        run: docker build . -t ${{ github.ref_name }} --target dev

      - name: Run unit tests
        run: docker run ${{ github.ref_name }} npm run test

  cd:
    needs: ci
    environment: staging
    env:
      DOCKER_IMAGE: '${{ vars.REGISTRY_USERNAME }}/plate:${{ github.ref_name }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Prod Docker image and push to registry
        uses: docker/build-push-action@v6.13.0
        with:
          target: prod
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.7'

      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Create namespace
        env:
          NAMESPACE: $(echo "${{ github.ref_name }}" | tr '_' '-')
        run: kubectl create namespace ${{ env.NAMESPACE }}

      - name: Setup kubeseal
        env:
          KUBESEAL_VERSION: 0.23.0
        run: |
          curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION:?}/kubeseal-${KUBESEAL_VERSION:?}-linux-amd64.tar.gz"
          tar -xvzf kubeseal-${KUBESEAL_VERSION:?}-linux-amd64.tar.gz kubeseal
          sudo install -m 755 kubeseal /usr/local/bin/kubeseal

      - name: Create sealed secret
        run: |
          kubectl create secret generic plate-secret \
            --namespace=${{ github.ref_name }} \
            --from-literal=POSTGRES_DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }} \
            --dry-run=client -o yaml | kubeseal -w ./k8s/helm/templates/sealed-secret.yaml

      - name: Setup helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.16.2

      - name: Build manifest
        run: |
          helm template plate ./k8s/helm \
          --values ./k8s/helm/dev-values.yaml \
          --set git.branch=${{ github.ref_name }} \
          --set app.image=${{ env.DOCKER_IMAGE }} > ./k8s/manifests/dev.yaml

      - name: Config git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit
        run: git commit -am "Builds K8S manifest"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.ref_name }}
