name: Deploy

on:
  push:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: 'README.md'
          folderId: 1T3HoI0zNEDuqqAPgF4OFcb4N9GwT-DR8
