apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - sealed-secret.yaml

patches:
  - path: deployment.yaml

namespace: dev
images:
  - name: appImage
    newName: lucasfernandesapp/plate
    newTag: main-7de597164be50f4c6ba69b372525f2e2948c0cd3
