---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plate-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_DATABASE_URL: AgB8q+RgKDmbINMV2sNIgeBMUB7CO0uWKNBlTkBcMJ7jLvHCxNmrJQZW49EOLCXWi36XpQs5aoZWOypU3HsHncgc9WZ9NLp/q48V3qCDrHZwN+gTkShIqUC2kSJp+t9wPnzK0U/LwyOUDzBjsEObbqLpR0BkWAIw2a9FFytmuISi4Y8aPRN8NC8oAE6zSO5PwndmGHNKCoSq9A9h9Q4SmyYa3d8mhRAt/3jw9ymXV9EkTCCCMCWrMc/1nBBBXVVHTLg45idmvJqIv3IcQ/CXzBbiAbgtN61m353EI05du+WV1uODL7R5b563jKYaRi4fjyhnSZAcNMjWqAexqk0GrE0HbxP1wYZ4JOZg/qdelEC5DyHaKu7cpEXoUsFskQUyLpayU+Q02Zd9+pmq45bxYCfmjUC6GvaVSbEtLOKkr0ZzYAWztuKEGiSi4E8CtfhSKYeQgZ+YNVO0x0N6S9xSHYMV4QuT19Rqkc8Bcl4X2WtP7Q/vXWwVyUJQyHMxgZJWo/em/loYyflvD9p8+dPaCQxQKKzyjyVf35RRERueKcAipLY/56xnZGoqgqmJPQp1mliTkuFt1oOaZj4NSsmPbt2irGqtgksNZOWozlIFJmojbZ0d548TVHW8DBqyoAesWMiE1NBpPJrqKgRyS/Xixj82jK+2KYyfT1AuN251eKrQ+8GyU8aeA8WYUt2SKhiXe6DKFT1C2sqc4dz8bIRp6pkp6xn/9mc8hP0MB320igrxUy4tCoYKBOawTr6LYba/PZUvHaYCXuW5vCND6B4p9NxsADS6e36iwkC9fLUtThgP76J111x3o1JataEmcV/Gt7IZpra+sTWdVwgj5xMTdCQ=
  template:
    metadata:
      creationTimestamp: null
      name: plate-secret
      namespace: dev
